import re

with open("src/App.tsx", "r", encoding="utf-8") as f:
    content = f.read()

translations_additions = {
    "US": """
    formulaGroupVideoImage: "Video — Image",
    formulaGroupVideoAudio: "Video — Audio",
    formulaGroupVideoTime: "Video — Time",
    formulaGroupVideoStream: "Video — Stream",
    formulaGroupAudioVol: "Audio — Volume",
    formulaGroupAudioChannel: "Audio — Channel / Sample",
    formulaGroupAudioFx: "Audio — Effects",
    formulaGroupAudioBitrate: "Audio — Bitrate / Trim",
    formulaGroupImageTransform: "Image — Transform",
    formulaGroupImageColor: "Image — Color",
    formulaGroupImageFx: "Image — Effects",
    formulaFormulas: "Formulas",
    
    fHflip: "Horizontal flip",
    fVflip: "Vertical flip",
    fTrans1: "Rotate 90° right",
    fTrans2: "Rotate 90° left",
    fGray: "Grayscale",
    fNegate: "Negative colors",
    fBright5: "Brightness +5%",
    fCont30: "Contrast +30%",
    fSat50: "Saturation +50%",
    fUnsharp: "Sharpen",
    fBoxblur: "Soft blur",
    fScale1280: "Width 1280px, auto height",
    fPadLetterbox: "Letterbox 1920x1080",
    fAn: "Remove audio track",
    fVn: "Extract audio only (no video)",
    fCaCopy: "Copy audio without re-encoding",
    fAfVol15: "Amplify audio +50%",
    fLoudnorm: "Normalize volume (EBU R128)",
    fSsTrim: "Trim: from 0:30, dur. 60s",
    fR30: "Fix FPS to 30",
    fR60: "Fix FPS to 60",
    fSetpts05: "Speed x2 (timelapse)",
    fSetpts20: "Slow motion x0.5",
    fCvCopy: "Copy video without re-encoding",
    fMovflags: "Optimize for web streaming",
    fThreads4: "Force 4 CPU threads",
    fBv2m: "Fixed bitrate 2 Mbps",
    fCrf18: "High quality (CRF 18)",
    fVol20: "Double volume (+100%)",
    fVol05: "Reduce to half",
    fDynaudnorm: "Dynamic normalization",
    fAgate: "Noise gate (silence)",
    fAc1: "Convert to Mono",
    fAc2: "Force Stereo",
    fAr44: "Sample rate 44.1 kHz (CD)",
    fAr48: "Sample rate 48 kHz (video)",
    fAr22: "Sample rate 22 kHz (web)",
    fAtempo15: "Speed x1.6 (no pitch change)",
    fAtempo075: "Speed x0.75 (no pitch change)",
    fAecho: "Echo / reverb",
    fHighpass: "High-pass filter 200 Hz",
    fLowpass: "Low-pass filter 3 kHz",
    fFadein: "3 second fade-in",
    fFadeout: "3 second fade-out",
    fTrimAud: "Trim: from 1:00, 30s",
    fBa320: "Bitrate 320 kbps (high quality)",
    fBa128: "Bitrate 128 kbps (standard)",
    fBa64: "Bitrate 64 kbps (saver)",
    fScale800: "Width 800px, proportional height",
    fCrop: "Crop left half",
    fTile: "3x3 Mosaic",
    fBright10: "Brightness +10%",
    fCont50: "Contrast +50%",
    fSat0: "Remove saturation (B&W)",
    fSatDouble: "Double saturation",
    fVintage: "Vintage effect",
    fGamma: "Gamma +50%",
    fUnsharpHigh: "Strong sharpen",
    fUnsharpLow: "Soft sharpen",
    fBoxblurGauss: "Gaussian blur",
    fNoise: "Add noise / grain",
    fVignette: "Dark vignette on edges",
    fEdge: "Edge detection",
    """,
    "ES": """
    formulaGroupVideoImage: "Video — Imagen",
    formulaGroupVideoAudio: "Video — Audio",
    formulaGroupVideoTime: "Video — Tiempo",
    formulaGroupVideoStream: "Video — Stream",
    formulaGroupAudioVol: "Audio — Volumen",
    formulaGroupAudioChannel: "Audio — Canal / Sample",
    formulaGroupAudioFx: "Audio — Efectos",
    formulaGroupAudioBitrate: "Audio — Bitrate / Corte",
    formulaGroupImageTransform: "Imagen — Transformar",
    formulaGroupImageColor: "Imagen — Color",
    formulaGroupImageFx: "Imagen — Efectos",
    formulaFormulas: "Fórmulas",
    
    fHflip: "Espejo horizontal",
    fVflip: "Voltear verticalmente",
    fTrans1: "Rotar 90° derecha",
    fTrans2: "Rotar 90° izquierda",
    fGray: "Escala de grises",
    fNegate: "Colores negativos",
    fBright5: "Brillo +5%",
    fCont30: "Contraste +30%",
    fSat50: "Saturación +50%",
    fUnsharp: "Nitidez (sharpen)",
    fBoxblur: "Desenfoque suave",
    fScale1280: "Ancho 1280px, alto auto",
    fPadLetterbox: "Letterbox 1920x1080",
    fAn: "Eliminar pista de audio",
    fVn: "Extraer solo audio (sin video)",
    fCaCopy: "Copiar audio sin recodificar",
    fAfVol15: "Amplificar audio +50%",
    fLoudnorm: "Normalizar volumen (EBU R128)",
    fSsTrim: "Recortar: desde 0:30, dur. 60s",
    fR30: "Fijar FPS a 30",
    fR60: "Fijar FPS a 60",
    fSetpts05: "Velocidad x2 (timelapse)",
    fSetpts20: "Camara lenta x0.5",
    fCvCopy: "Copiar video sin recodificar",
    fMovflags: "Optimizar para streaming web",
    fThreads4: "Forzar 4 hilos de CPU",
    fBv2m: "Bitrate fijo 2 Mbps",
    fCrf18: "Calidad alta (CRF 18)",
    fVol20: "Doblar volumen (+100%)",
    fVol05: "Reducir a la mitad",
    fDynaudnorm: "Normalizacion dinamica",
    fAgate: "Noise gate (silencio)",
    fAc1: "Convertir a Mono",
    fAc2: "Forzar Stereo",
    fAr44: "Sample rate 44.1 kHz (CD)",
    fAr48: "Sample rate 48 kHz (video)",
    fAr22: "Sample rate 22 kHz (web)",
    fAtempo15: "Velocidad x1.6 (sin pitch)",
    fAtempo075: "Velocidad x0.75 (sin pitch)",
    fAecho: "Eco / reverb",
    fHighpass: "Filtro high-pass 200 Hz",
    fLowpass: "Filtro low-pass 3 kHz",
    fFadein: "Fade-in de 3 segundos",
    fFadeout: "Fade-out de 3 segundos",
    fTrimAud: "Recortar: desde 1:00, 30s",
    fBa320: "Bitrate 320 kbps (alta calidad)",
    fBa128: "Bitrate 128 kbps (estandar)",
    fBa64: "Bitrate 64 kbps (ahorro)",
    fScale800: "Ancho 800px, alto proporcional",
    fCrop: "Recortar mitad izquierda",
    fTile: "Mosaico 3x3",
    fBright10: "Brillo +10%",
    fCont50: "Contraste +50%",
    fSat0: "Quitar saturacion (BN)",
    fSatDouble: "Saturacion doble",
    fVintage: "Efecto vintage",
    fGamma: "Gamma +50%",
    fUnsharpHigh: "Sharpen fuerte",
    fUnsharpLow: "Sharpen suave",
    fBoxblurGauss: "Desenfoque gaussiano",
    fNoise: "Añadir ruido / grano",
    fVignette: "Viñeta oscura en bordes",
    fEdge: "Deteccion de bordes",
    """,
    "FR": """
    formulaGroupVideoImage: "Vidéo — Image",
    formulaGroupVideoAudio: "Vidéo — Audio",
    formulaGroupVideoTime: "Vidéo — Temps",
    formulaGroupVideoStream: "Vidéo — Stream",
    formulaGroupAudioVol: "Audio — Volume",
    formulaGroupAudioChannel: "Audio — Canal / Échantillon",
    formulaGroupAudioFx: "Audio — Effets",
    formulaGroupAudioBitrate: "Audio — Débit / Découpe",
    formulaGroupImageTransform: "Image — Transformer",
    formulaGroupImageColor: "Image — Couleur",
    formulaGroupImageFx: "Image — Effets",
    formulaFormulas: "Formules",
    
    fHflip: "Miroir horizontal",
    fVflip: "Retourner verticalement",
    fTrans1: "Pivoter 90° à droite",
    fTrans2: "Pivoter 90° à gauche",
    fGray: "Niveaux de gris",
    fNegate: "Couleurs négatives",
    fBright5: "Luminosité +5%",
    fCont30: "Contraste +30%",
    fSat50: "Saturation +50%",
    fUnsharp: "Netteté (sharpen)",
    fBoxblur: "Flou doux",
    fScale1280: "Largeur 1280px, hauteur auto",
    fPadLetterbox: "Letterbox 1920x1080",
    fAn: "Supprimer la piste audio",
    fVn: "Extraire l'audio uniquement",
    fCaCopy: "Copier l'audio sans réencoder",
    fAfVol15: "Amplifier l'audio +50%",
    fLoudnorm: "Normaliser le volume (EBU R128)",
    fSsTrim: "Découper : de 0:30, dur. 60s",
    fR30: "Fixer FPS à 30",
    fR60: "Fixer FPS à 60",
    fSetpts05: "Vitesse x2 (timelapse)",
    fSetpts20: "Ralenti x0.5",
    fCvCopy: "Copier la vidéo sans réencoder",
    fMovflags: "Optimiser pour le web streaming",
    fThreads4: "Forcer 4 threads CPU",
    fBv2m: "Débit fixe 2 Mbps",
    fCrf18: "Haute qualité (CRF 18)",
    fVol20: "Double volume (+100%)",
    fVol05: "Réduire de moitié",
    fDynaudnorm: "Normalisation dynamique",
    fAgate: "Noise gate (silence)",
    fAc1: "Convertir en Mono",
    fAc2: "Forcer Stéréo",
    fAr44: "Taux d'échantillonnage 44.1 kHz",
    fAr48: "Taux d'échantillonnage 48 kHz",
    fAr22: "Taux d'échantillonnage 22 kHz",
    fAtempo15: "Vitesse x1.6 (sans changer le pitch)",
    fAtempo075: "Vitesse x0.75 (sans changer le pitch)",
    fAecho: "Écho / réverbération",
    fHighpass: "Filtre passe-haut 200 Hz",
    fLowpass: "Filtre passe-bas 3 kHz",
    fFadein: "Fondu entrant 3 secondes",
    fFadeout: "Fondu sortant 3 secondes",
    fTrimAud: "Découper : de 1:00, 30s",
    fBa320: "Débit 320 kbps (haute qualité)",
    fBa128: "Débit 128 kbps (standard)",
    fBa64: "Débit 64 kbps (économie)",
    fScale800: "Largeur 800px, hauteur prop.",
    fCrop: "Recadrer moitié gauche",
    fTile: "Mosaïque 3x3",
    fBright10: "Luminosité +10%",
    fCont50: "Contraste +50%",
    fSat0: "Supprimer saturation (N&B)",
    fSatDouble: "Saturation double",
    fVintage: "Effet vintage",
    fGamma: "Gamma +50%",
    fUnsharpHigh: "Netteté forte",
    fUnsharpLow: "Netteté douce",
    fBoxblurGauss: "Flou gaussien",
    fNoise: "Ajouter du bruit / grain",
    fVignette: "Vignette sombre sur les bords",
    fEdge: "Détection des contours",
    """,
    "JP": """
    formulaGroupVideoImage: "ビデオ — 画像",
    formulaGroupVideoAudio: "ビデオ — 音声",
    formulaGroupVideoTime: "ビデオ — 時間",
    formulaGroupVideoStream: "ビデオ — ストリーム",
    formulaGroupAudioVol: "音声 — 音量",
    formulaGroupAudioChannel: "音声 — チャンネル/サンプル",
    formulaGroupAudioFx: "音声 — エフェクト",
    formulaGroupAudioBitrate: "音声 — ビットレート/トリム",
    formulaGroupImageTransform: "画像 — 変形",
    formulaGroupImageColor: "画像 — 色彩",
    formulaGroupImageFx: "画像 — エフェクト",
    formulaFormulas: "数式 (Formulas)",
    
    fHflip: "左右反転",
    fVflip: "上下反転",
    fTrans1: "右に90度回転",
    fTrans2: "左に90度回転",
    fGray: "グレースケール",
    fNegate: "色を反転",
    fBright5: "明るさ +5%",
    fCont30: "コントラスト +30%",
    fSat50: "彩度 +50%",
    fUnsharp: "シャープネス",
    fBoxblur: "ソフトなぼかし",
    fScale1280: "幅1280px、高さ自動",
    fPadLetterbox: "レターボックス 1920x1080",
    fAn: "音声トラックを削除",
    fVn: "音声のみ抽出",
    fCaCopy: "再エンコードせずに音声をコピー",
    fAfVol15: "音量を+50%増幅",
    fLoudnorm: "音量を正規化 (EBU R128)",
    fSsTrim: "トリミング: 0:30から、長さ60秒",
    fR30: "FPSを30に固定",
    fR60: "FPSを60に固定",
    fSetpts05: "速度x2 (タイムラプス)",
    fSetpts20: "スローモーションx0.5",
    fCvCopy: "再エンコードせずにビデオをコピー",
    fMovflags: "Webストリーミング用に最適化",
    fThreads4: "4 CPUスレッドを強制",
    fBv2m: "固定ビットレート 2 Mbps",
    fCrf18: "高品質 (CRF 18)",
    fVol20: "音量を2倍 (+100%)",
    fVol05: "音量を半分に減らす",
    fDynaudnorm: "動的正規化",
    fAgate: "ノイズゲート (無音)",
    fAc1: "モノラルに変換",
    fAc2: "ステレオを強制",
    fAr44: "サンプルレート 44.1 kHz (CD)",
    fAr48: "サンプルレート 48 kHz (ビデオ)",
    fAr22: "サンプルレート 22 kHz (Web)",
    fAtempo15: "速度 x1.6 (ピッチ変更なし)",
    fAtempo075: "速度 x0.75 (ピッチ変更なし)",
    fAecho: "エコー / リバーブ",
    fHighpass: "ハイパスフィルター 200 Hz",
    fLowpass: "ローパスフィルター 3 kHz",
    fFadein: "3秒のフェードイン",
    fFadeout: "3秒のフェードアウト",
    fTrimAud: "トリミング: 1:00から、長さ30秒",
    fBa320: "ビットレート 320 kbps (高品質)",
    fBa128: "ビットレート 128 kbps (標準)",
    fBa64: "ビットレート 64 kbps (節約)",
    fScale800: "幅800px、高さ比例",
    fCrop: "左半分を切り抜き",
    fTile: "3x3 モザイク",
    fBright10: "明るさ +10%",
    fCont50: "コントラスト +50%",
    fSat0: "彩度を削除 (白黒)",
    fSatDouble: "彩度を2倍",
    fVintage: "ヴィンテージ効果",
    fGamma: "ガンマ +50%",
    fUnsharpHigh: "強いシャープネス",
    fUnsharpLow: "弱いシャープネス",
    fBoxblurGauss: "ガウスぼかし",
    fNoise: "ノイズ/粒子を追加",
    fVignette: "エッジに暗いビネット",
    fEdge: "エッジ検出",
    """,
    "CN": """
    formulaGroupVideoImage: "视频 — 图像",
    formulaGroupVideoAudio: "视频 — 音频",
    formulaGroupVideoTime: "视频 — 时间",
    formulaGroupVideoStream: "视频 — 流",
    formulaGroupAudioVol: "音频 — 音量",
    formulaGroupAudioChannel: "音频 — 通道/采样",
    formulaGroupAudioFx: "音频 — 效果",
    formulaGroupAudioBitrate: "音频 — 比特率/剪裁",
    formulaGroupImageTransform: "图像 — 变换",
    formulaGroupImageColor: "图像 — 颜色",
    formulaGroupImageFx: "图像 — 效果",
    formulaFormulas: "公式 (Formulas)",
    
    fHflip: "水平翻转",
    fVflip: "垂直翻转",
    fTrans1: "向右旋转90度",
    fTrans2: "向左旋转90度",
    fGray: "灰度",
    fNegate: "反色",
    fBright5: "亮度 +5%",
    fCont30: "对比度 +30%",
    fSat50: "饱和度 +50%",
    fUnsharp: "锐化",
    fBoxblur: "柔和模糊",
    fScale1280: "宽 1280px，高自动",
    fPadLetterbox: "信箱模式 1920x1080",
    fAn: "移除音频轨",
    fVn: "仅提取音频",
    fCaCopy: "不重新编码复制音频",
    fAfVol15: "放大音频 +50%",
    fLoudnorm: "音量标准化 (EBU R128)",
    fSsTrim: "修剪：从 0:30，时长 60s",
    fR30: "固定FPS为30",
    fR60: "固定FPS为60",
    fSetpts05: "速度x2 (延时摄影)",
    fSetpts20: "慢动作x0.5",
    fCvCopy: "不重新编码复制视频",
    fMovflags: "为Web流媒体优化",
    fThreads4: "强制4个CPU线程",
    fBv2m: "固定比特率 2 Mbps",
    fCrf18: "高质量 (CRF 18)",
    fVol20: "双倍音量 (+100%)",
    fVol05: "减半音量",
    fDynaudnorm: "动态标准化",
    fAgate: "噪声门限 (静音)",
    fAc1: "转换为单声道",
    fAc2: "强制立体声",
    fAr44: "采样率 44.1 kHz (CD)",
    fAr48: "采样率 48 kHz (视频)",
    fAr22: "采样率 22 kHz (Web)",
    fAtempo15: "速度 x1.6 (不变调)",
    fAtempo075: "速度 x0.75 (不变调)",
    fAecho: "回声 / 混响",
    fHighpass: "高通滤波器 200 Hz",
    fLowpass: "低通滤波器 3 kHz",
    fFadein: "3秒淡入",
    fFadeout: "3秒淡出",
    fTrimAud: "修剪：从 1:00，时长 30s",
    fBa320: "比特率 320 kbps (高质量)",
    fBa128: "比特率 128 kbps (标准)",
    fBa64: "比特率 64 kbps (节省)",
    fScale800: "宽 800px，高按比例",
    fCrop: "裁剪左半部分",
    fTile: "3x3 马赛克",
    fBright10: "亮度 +10%",
    fCont50: "对比度 +50%",
    fSat0: "去除饱和度 (黑白)",
    fSatDouble: "双倍饱和度",
    fVintage: "复古效果",
    fGamma: "伽马 +50%",
    fUnsharpHigh: "强锐化",
    fUnsharpLow: "柔和锐化",
    fBoxblurGauss: "高斯模糊",
    fNoise: "添加噪点/颗粒",
    fVignette: "边缘暗角",
    fEdge: "边缘检测",
    """
}

# Add translations to each block
for lang, keys in translations_additions.items():
    pattern = r"(" + lang + r": \{)(.*?)(cacheSkip: [^\n]+\n[ \t]*\})"
    
    def repl(m):
        return m.group(1) + m.group(2) + m.group(3)[:-1] + ",\n" + keys + m.group(3)[-1]
        
    content = re.sub(pattern, repl, content, flags=re.DOTALL)

# Now replace the formulas arrays in App.tsx
formulas_replacement = """
                const videoGroups: FormulaGroup[] = [
                  { group: t("formulaGroupVideoImage"), items: [
                    { cmd: "-vf hflip", desc: t("fHflip") },
                    { cmd: "-vf vflip", desc: t("fVflip") },
                    { cmd: "-vf transpose=1", desc: t("fTrans1") },
                    { cmd: "-vf transpose=2", desc: t("fTrans2") },
                    { cmd: "-vf format=gray", desc: t("fGray") },
                    { cmd: "-vf negate", desc: t("fNegate") },
                    { cmd: "-vf eq=brightness=0.05", desc: t("fBright5") },
                    { cmd: "-vf eq=contrast=1.3", desc: t("fCont30") },
                    { cmd: "-vf eq=saturation=1.6", desc: t("fSat50") },
                    { cmd: "-vf unsharp=5:5:1.6", desc: t("fUnsharp") },
                    { cmd: "-vf boxblur=2:2", desc: t("fBoxblur") },
                    { cmd: "-vf scale=1280:-2", desc: t("fScale1280") },
                    { cmd: "-vf pad=1920:1080:(ow-iw)/2:(oh-ih)/2", desc: t("fPadLetterbox") },
                  ]},
                  { group: t("formulaGroupVideoAudio"), items: [
                    { cmd: "-an", desc: t("fAn") },
                    { cmd: "-vn", desc: t("fVn") },
                    { cmd: "-c:a copy", desc: t("fCaCopy") },
                    { cmd: "-af volume=1.6", desc: t("fAfVol15") },
                    { cmd: "-af loudnorm", desc: t("fLoudnorm") },
                  ]},
                  { group: t("formulaGroupVideoTime"), items: [
                    { cmd: "-ss 00:00:30 -t 60", desc: t("fSsTrim") },
                    { cmd: "-r 30", desc: t("fR30") },
                    { cmd: "-r 60", desc: t("fR60") },
                    { cmd: "-vf setpts=0.5*PTS", desc: t("fSetpts05") },
                    { cmd: "-vf setpts=2.0*PTS", desc: t("fSetpts20") },
                  ]},
                  { group: t("formulaGroupVideoStream"), items: [
                    { cmd: "-c:v copy", desc: t("fCvCopy") },
                    { cmd: "-movflags +faststart", desc: t("fMovflags") },
                    { cmd: "-threads 4", desc: t("fThreads4") },
                    { cmd: "-b:v 2M", desc: t("fBv2m") },
                    { cmd: "-crf 18", desc: t("fCrf18") },
                  ]},
                ];
                const audioGroups: FormulaGroup[] = [
                  { group: t("formulaGroupAudioVol"), items: [
                    { cmd: "-af volume=2.0", desc: t("fVol20") },
                    { cmd: "-af volume=1.6", desc: t("fAfVol15") },
                    { cmd: "-af volume=0.5", desc: t("fVol05") },
                    { cmd: "-af loudnorm", desc: t("fLoudnorm") },
                    { cmd: "-af dynaudnorm", desc: t("fDynaudnorm") },
                    { cmd: "-af agate", desc: t("fAgate") },
                  ]},
                  { group: t("formulaGroupAudioChannel"), items: [
                    { cmd: "-ac 1", desc: t("fAc1") },
                    { cmd: "-ac 2", desc: t("fAc2") },
                    { cmd: "-ar 44100", desc: t("fAr44") },
                    { cmd: "-ar 48000", desc: t("fAr48") },
                    { cmd: "-ar 22050", desc: t("fAr22") },
                  ]},
                  { group: t("formulaGroupAudioFx"), items: [
                    { cmd: "-af atempo=1.6", desc: t("fAtempo15") },
                    { cmd: "-af atempo=0.75", desc: t("fAtempo075") },
                    { cmd: "-af aecho=0.8:0.9:500:0.3", desc: t("fAecho") },
                    { cmd: "-af highpass=f=200", desc: t("fHighpass") },
                    { cmd: "-af lowpass=f=3000", desc: t("fLowpass") },
                    { cmd: "-af afade=t=in:d=3", desc: t("fFadein") },
                    { cmd: "-af afade=t=out:d=3", desc: t("fFadeout") },
                  ]},
                  { group: t("formulaGroupAudioBitrate"), items: [
                    { cmd: "-ss 00:01:00 -t 30", desc: t("fTrimAud") },
                    { cmd: "-c:a copy", desc: t("fCaCopy") },
                    { cmd: "-b:a 320k", desc: t("fBa320") },
                    { cmd: "-b:a 128k", desc: t("fBa128") },
                    { cmd: "-b:a 64k", desc: t("fBa64") },
                  ]},
                ];
                const imageGroups: FormulaGroup[] = [
                  { group: t("formulaGroupImageTransform"), items: [
                    { cmd: "-vf hflip", desc: t("fHflip") },
                    { cmd: "-vf vflip", desc: t("fVflip") },
                    { cmd: "-vf transpose=1", desc: t("fTrans1") },
                    { cmd: "-vf transpose=2", desc: t("fTrans2") },
                    { cmd: "-vf scale=800:-1", desc: t("fScale800") },
                    { cmd: "-vf crop=iw/2:ih:0:0", desc: t("fCrop") },
                    { cmd: "-vf tile=3x3", desc: t("fTile") },
                  ]},
                  { group: t("formulaGroupImageColor"), items: [
                    { cmd: "-vf format=gray", desc: t("fGray") },
                    { cmd: "-vf negate", desc: t("fNegate") },
                    { cmd: "-vf eq=brightness=0.1", desc: t("fBright10") },
                    { cmd: "-vf eq=contrast=1.6", desc: t("fCont50") },
                    { cmd: "-vf eq=saturation=0", desc: t("fSat0") },
                    { cmd: "-vf eq=saturation=2", desc: t("fSatDouble") },
                    { cmd: "-vf curves=vintage", desc: t("fVintage") },
                    { cmd: "-vf eq=gamma=1.6", desc: t("fGamma") },
                  ]},
                  { group: t("formulaGroupImageFx"), items: [
                    { cmd: "-vf unsharp=5:5:2.0", desc: t("fUnsharpHigh") },
                    { cmd: "-vf unsharp=3:3:0.5", desc: t("fUnsharpLow") },
                    { cmd: "-vf boxblur=4:4", desc: t("fBoxblurGauss") },
                    { cmd: "-vf noise=alls=20:allf=t", desc: t("fNoise") },
                    { cmd: "-vf vignette", desc: t("fVignette") },
                    { cmd: "-vf edgedetect", desc: t("fEdge") },
                  ]},
                ];"""

import re
# Regex to match the videoGroups, audioGroups and imageGroups
# Starts at `const videoGroups: FormulaGroup[] = [`
# Ends at `];` of imageGroups

pattern_groups = r"const videoGroups: FormulaGroup\[\] = \[.*?const imageGroups: FormulaGroup\[\] = \[.*?\];"
content = re.sub(pattern_groups, formulas_replacement.strip(), content, flags=re.DOTALL)

# Replace the text-blue-500 with THEME_COLORS[themeColor].textPrimary
pattern_cmd = r"`shrink-0 font-mono text-\[10px\] font-semibold \$\{customArgs === ex\.cmd \? THEME_COLORS\[themeColor\]\.textSimple : \"text-blue-500\"}`"
replacement_cmd = r"`shrink-0 font-mono text-[10px] font-semibold ${customArgs === ex.cmd ? THEME_COLORS[themeColor].textSimple : THEME_COLORS[themeColor].textPrimary}`"
content = content.replace(pattern_cmd, replacement_cmd)

# Also replace the span "Fórmulas" text in the buttons to be translated
content = content.replace("<span>Fórmulas</span>", "<span>{t(\"formulaFormulas\")}</span>")

# Write it back
with open("src/App.tsx", "w", encoding="utf-8") as f:
    f.write(content)

print("Done")
